### ISSUE TITLE
Ajustar a distância entre as bandeiras do idioma

### ISSUE THREAD

**Issue by jamilatta** [scieloorg/opac#641]

**Comment by jamilatta** [comment]
@caramez poderia nos ajudar nessa tarefa? 

A equipe percebeu que as bandeirar de idiomas esta com distância diferente entre a página do artigo e as demais páginas.

**Comment by jfunez** [comment]
@caramez eu [fiz um ajuste no css](https://github.com/scieloorg/opac/pull/666/files#diff-9bfc60d45981d9b4bdcbda8d744a34b1R88) para consertar (temporariamente) o problema. redefini as classes de CSS num arquivo `styles.css` que carregamos após incluir os "bundles". Porém o "conserto" esta longe de ser o ideal.

Pontualmente a mudança foi: 

```css

.article .journalMenu .language a,
.journal .journalMenu .language a {
    margin-left: 15px;
}

.article .journalMenu .language a:last-child,
.journal .journalMenu .language a:last-child {
    position: relative;
    top: 0;
}
```

A solução definitiva deve ser feita nos bundles por vocês. assim podemos remover este "hack" no `styles.css`
